# Generated by Django 4.2.7 on 2023-12-19 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrobomba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(blank=True, max_length=100, verbose_name='Elemento')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('observaciones', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('fecha_revision', models.DateField(verbose_name='Fecha de Revisión')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrobomba.carro', verbose_name='Carro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
