# Generated by Django 4.2.7 on 2023-12-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad')),
                ('patente', models.CharField(max_length=20, verbose_name='Patente')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
            ],
        ),
    ]
